pipeline {
    agent any

    parameters {
        string(name: 'S3_URL', defaultValue: 'http://mlops-minio:4000', description: '')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'dev', url: 'https://github.com/kavlab/mlops-project/'
            }
        }

        stage('Prepare') {
            steps {
                dir('src') {
                    sh """python3 -m venv .venv
                    . .venv/bin/activate
                    pip install -r ./requirements.txt
                    pip install dvc dvc-s3"""
                }
            }
        }

        stage('Configure DVC') {
            steps {
                dir('src') {
                    withCredentials([usernamePassword(credentialsId: 'S3', passwordVariable: 'S3_SECRET_ACCESS_KEY', usernameVariable: 'S3_ACCESS_KEY_ID')]) {
                        sh """. .venv/bin/activate
                        cd ..
                        dvc init -f
                        dvc remote add -f -d data_storage s3://mlops-files/data
                        echo "${params.S3_URL}"
                        dvc remote modify data_storage endpointurl ${params.S3_URL}
                        dvc remote modify data_storage access_key_id ${S3_ACCESS_KEY_ID}
                        dvc remote modify data_storage secret_access_key ${S3_SECRET_ACCESS_KEY}
                        dvc remote modify data_storage use_ssl false
                        rm -rf src/datasets
                        mkdir src/datasets
                        dvc add src/datasets"""
                    }
                }
            }
        }

        stage('Load data') {
            steps {
                dir('src') {
                    sh """. .venv/bin/activate
                    python3 ./data/load_dataset.py"""
                }
            }
        }

        stage('Data processing') {
            steps {
                dir('src') {
                    sh """. .venv/bin/activate
                    python3 ./features/build_features.py"""
                }
            }
        }

        stage('Model training') {
            steps {
                dir('src') {
                    sh """. .venv/bin/activate
                    python3 ./models/train_model.py"""
                }
            }
        }

        stage('Push model and data') {
            steps {
                dir('src') {
                    sh """. .venv/bin/activate
                    dvc push"""
                }
            }
        }
    }
}
